# Generated by Django 4.1.3 on 2022-12-08 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAnimations', models.SmallIntegerField(default=1)),
                ('nextLandmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('title', models.CharField(default='Untitled Learning Map', max_length=50)),
                ('publicity', models.CharField(choices=[('v', 'Visible'), ('p', 'Personal')], default='p', max_length=1)),
                ('description', models.CharField(max_length=500, null=True)),
                ('topic', models.CharField(choices=[('CSC', 'Computer Science'), ('PHY', 'Physics'), ('MAT', 'Mathematics')], max_length=3, null=True)),
                ('lastSaved', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmarkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='ShapeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmarkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMainPath', models.BooleanField()),
                ('mapId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.map')),
            ],
        ),
        migrations.CreateModel(
            name='LegendEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.BooleanField()),
                ('landmarkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legend', to='config.landmark')),
                ('nextEntry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.legendentry')),
            ],
        ),
        migrations.AddField(
            model_name='landmark',
            name='pathId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='config.path'),
        ),
        migrations.CreateModel(
            name='ImageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image', models.FileField(upload_to='media/')),
                ('animationAppearance', models.SmallIntegerField(default=0)),
                ('landmarkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='config.landmark')),
            ],
        ),
    ]
