# Generated by Django 4.1.3 on 2022-11-26 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='pathId',
        ),
        migrations.AddField(
            model_name='landmark',
            name='mapId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.path'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landmark',
            name='previousLandmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.landmark'),
        ),
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='publicity',
            field=models.CharField(choices=[('p', 'Personal'), ('v', 'Visible')], max_length=1),
        ),
        migrations.AlterField(
            model_name='map',
            name='topic',
            field=models.CharField(choices=[('MAT', 'Mathematics'), ('PHY', 'Physics')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='mapId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.map'),
        ),
    ]
