# Generated by Django 4.1.3 on 2022-12-08 19:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legendentry',
            name='landmarkId',
        ),
        migrations.RemoveField(
            model_name='legendentry',
            name='nextEntry',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.RemoveField(
            model_name='shapebox',
            name='landmarkId',
        ),
        migrations.RemoveField(
            model_name='textbox',
            name='landmarkId',
        ),
        migrations.AddField(
            model_name='imagebox',
            name='transformation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[1, 0, 0, 1, 0, 0], size=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagebox',
            name='image',
            field=models.FileField(unique=True, upload_to='image-boxes/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='publicity',
            field=models.CharField(choices=[('p', 'Personal'), ('v', 'Visible')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='map',
            name='topic',
            field=models.CharField(choices=[('PHY', 'Physics'), ('MAT', 'Mathematics'), ('CSC', 'Computer Science')], max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='LegendEntry',
        ),
        migrations.DeleteModel(
            name='ShapeBox',
        ),
        migrations.DeleteModel(
            name='TextBox',
        ),
    ]
