# Generated by Django 4.1.3 on 2022-11-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_remove_landmark_pathid_landmark_mapid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='mapId',
            new_name='pathId',
        ),
        migrations.AlterField(
            model_name='map',
            name='publicity',
            field=models.CharField(choices=[('v', 'Visible'), ('p', 'Personal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='map',
            name='topic',
            field=models.CharField(choices=[('PHY', 'Physics'), ('MAT', 'Mathematics')], max_length=3, null=True),
        ),
    ]
