# Generated by Django 4.1.3 on 2022-12-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_imagebox_transformation_alter_map_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='nextLandmark',
            new_name='previousLandmark',
        ),
        migrations.AlterField(
            model_name='map',
            name='publicity',
            field=models.CharField(choices=[('v', 'Visible'), ('p', 'Personal')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='map',
            name='topic',
            field=models.CharField(choices=[('MAT', 'Mathematics'), ('CSC', 'Computer Science'), ('PHY', 'Physics')], max_length=3, null=True),
        ),
    ]
