# Generated by Django 4.1.3 on 2022-12-03 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_rename_mapid_landmark_pathid_alter_map_publicity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='lastSaved',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landmark',
            name='numAnimations',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='map',
            name='publicity',
            field=models.CharField(choices=[('p', 'Personal'), ('v', 'Visible')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.CharField(default='Untitled Learning Map', max_length=50),
        ),
        migrations.CreateModel(
            name='TextBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmarkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='ShapeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmarkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='LegendEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.BooleanField()),
                ('landmarkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.landmark')),
                ('nextEntry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.legendentry')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmarkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.landmark')),
            ],
        ),
    ]
