# Generated by Django 4.1.3 on 2022-12-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_notifications_map_lastsaved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebox',
            name='landmarkId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='config.landmark'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='pathId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmark', to='config.path'),
        ),
        migrations.AlterField(
            model_name='legendentry',
            name='landmarkId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legend', to='config.landmark'),
        ),
        migrations.AlterField(
            model_name='map',
            name='lastSaved',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='topic',
            field=models.CharField(choices=[('PHY', 'Physics'), ('CSC', 'Computer Science'), ('MAT', 'Mathematics')], max_length=3, null=True),
        ),
    ]
