# Generated by Django 4.1.3 on 2022-12-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_rename_nextlandmark_landmark_previouslandmark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='previousLandmark',
        ),
        migrations.AddField(
            model_name='landmark',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='topic',
            field=models.CharField(choices=[('PHY', 'Physics'), ('CSC', 'Computer Science'), ('MAT', 'Mathematics')], max_length=3, null=True),
        ),
    ]
