# Generated by Django 4.1.3 on 2022-12-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_imagebox_landmarkid_alter_landmark_pathid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='previousLandmark',
            new_name='nextLandmark',
        ),
        migrations.AlterField(
            model_name='map',
            name='publicity',
            field=models.CharField(choices=[('v', 'Visible'), ('p', 'Personal')], default='p', max_length=1),
        ),
    ]
