# Generated by Django 4.1.3 on 2022-12-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_remove_landmark_previouslandmark_landmark_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='publicity',
            field=models.CharField(choices=[('p', 'Personal'), ('v', 'Visible')], default='p', max_length=1),
        ),
    ]
