# Generated by Django 4.1.3 on 2022-12-09 23:17

import config.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_alter_map_publicity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmark',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='map',
            name='publicity',
            field=models.CharField(choices=[('v', 'Visible'), ('p', 'Personal')], default='p', max_length=1),
        ),
        migrations.CreateModel(
            name='ShapeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.CharField(max_length=500)),
                ('transformation', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=config.models.defaultTransformation, size=6)),
                ('animationAppearance', models.SmallIntegerField(default=0)),
                ('landmarkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='config.landmark')),
            ],
        ),
    ]
